### ISSUE TITLE
Enable multiple-GPU processing?

### ISSUE THREAD

**Issue by hanfeisun** [pender/chatbot-rnn#11]
It seems that only one CPU could be used for the lib. Would it be possible for me to know whether there is a plan to develop a multiple-GPU version? How hard would that be?

**Comment by hanfeisun** [comment]
Also I find the `train.py` seems to always run on `gpu:0`.. Would it be possible to make it run on other gpus?

**Comment by pender** [comment]
Not planning to add these features (among other reasons, I couldn't test them since I have only one GPU installed myself).

**Comment by neofob** [comment]
@hanfeisun : You can specify which GPU(s) available to `tensorflow` to use by setting the environment variable `CUDA_VISIBLE_DEVICES`. For example, setting the GPU `1` visible to `CUDA_VISIBLE_DEVICES=1`

Or, the order of them, `1,0` instead of `0,1` to `tensorflow`; `CUDA_VISIBLE_DEVICES=1,0`

Reference: https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/
